version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package
      - cp target/hello-lambda-1.0-SNAPSHOT.jar $CODEBUILD_SRC_DIR/hello-lambda.jar
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/hello-lambda.jar
